import { IProduct } from "@utils/@types/sqlite/product"

export const buildProductUpdateParams = (p: IProduct) => [
  p.oid,
  p.org_id,
  p.name,
  p.image,
  p.status,
  p.type,
  p.group_id,
  p.warehouse_type,
  p.description1,
  p.description2,
  p.has_variable,
  p.has_courtesy,
  p.has_control,
  p.has_cut,
  p.has_tolerance,
  p.print_qrcode,
  p.print_ticket,
  p.print_local,
  p.print_date,
  p.print_value,
  p.print_group,
  p.print_plate,
  p.print_tolerance,
  p.price_cost,
  p.price_sell,
  p.quantity,
  p.start_at,
  p.number_copy,
  p.time_tolerance,
  p.value_tolerance,
  p.created_at,
  p.updated_at,
  1, // synced
  p.archived ?? 0,
  p.id, // WHERE id = ?
]
